### ISSUE TITLE
Problème de connexion

### ISSUE THREAD

**Issue by tduhautb** [simde-utc/portail#111]
Lorsque j'essaie de me connecter en CAS j'ai le message d'erreur suivant : "Whoops, looks like something went wrong.", idem en navigation privée. Si je reviens sur le portail après, la connexion n'a pas fonctionné.

**Comment by NastuzziSamy** [comment]
Oki je vois d'où vient le problème, c'est parce que tu as déjà un compte relié au CAS mais que ton email a changé entre temps

Btw, gg le hds :p

**Comment by NastuzziSamy** [comment]
Corrigé et en prod :)

**Comment by tduhautb** [comment]
De mon point de vue, "corrigé et en prod" = faux si "en prod" veut dire "en ligne sur l'adresse standard tu peux te connecter maintenant".
En bref j'ai toujours le souci, à toi de me dire si c'est normal et ça va arriver ou pas ;)

**Comment by Chostakovitch** [comment]
@NastuzziSamy Même problème pour moi, probablement dû au changement d'email également. Peux-tu checker ? J'ai besoin du portail :p

**Comment by NastuzziSamy** [comment]
@tduhautb @Chostakovitch , normalement c'est bon pour vous, tenez moi au courant :)

**Comment by Chostakovitch** [comment]
@NastuzziSamy c'est ok, merci!
