### ISSUE TITLE
Page de profile vide

### ISSUE THREAD

**Issue by cesar-richard** [simde-utc/portail#114]
La page est vide et l'entête est incohérent
J'ai eu ces titres par exemple
Profile - Undefined 
Simde - membres
Etusexy

**Comment by jjerphan** [comment]
Idem pour les profils personnel : page blanche.

**Comment by r0one** [comment]
J'arrive pas à reproduire ces problèmes, par contre il est vrai qu'on devrait implémenter des pages personnelles sur les utilisateurs.

**Comment by MercierCorentin** [comment]
The following PRs are part of the profile development.
- #261 Associative Career front
- #264 Contributions back
- #272 Contributions front
- #292 Authorized clients + revoke possibility
- #296 Hotfix 
- #297 My personnal information
- #301 Old PRs stabilization

**Comment by MercierCorentin** [comment]
As the profile feature is in production, we're considering this feature request as completed! See previous comment for more details.
