### ISSUE TITLE
Japon'UTC non présente sur le nouveau portail

### ISSUE THREAD

**Issue by MclMath** [simde-utc/portail#116]
Bonjour,

L'association Japon'UTC n'apparaît pas sur le nouveau portail, alors qu'elle apparaissait sur l'ancien portail. Est-ce un problème lié à la migration ou un oubli?

Cordialement,

Michaël Mahamat, secrétaire de Japon'UTC pour P19.

**Comment by NastuzziSamy** [comment]
Salut, c'est corrigé, désolé pour le dérangement
