### ISSUE TITLE
identifiants uniques pour les articles

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#12]
pour pouvoir afficher des articles au hasard, il faut qu'en local je sache quels articles j'ai déjà affichés à l'utilisateur

**Comment by NastuzziSamy** [comment]
Hmmm, la fonction hasard est universelle ici 

Je pense que le mieux c'est de rajouter une condition dans la requête avant le random : 
```php 
if ($request->input('order') === 'random')
 $articles = Article::whereNotIn('id', $articleIdsReadByUser);
else 
 $articles = new Article; 

return response()->json($articles->getSelection());
```

**Comment by NastuzziSamy** [comment]
En fait nan @CdRom1 j'ai dit n'importe quoi. 

Tout simplement avec mon paquet de Sélection il suffit de créer un scope qu'on appelle `user` et on donne deux possibilités : 
- `seen` pour avoir les articles vuent par l'utilisateur 
- `liked` que l'utilisateur a liké 
- `new` que l'utilisateur n'a pas encore vu 

Et on ajoute dans les sélections possibles `'user' => null` 

C'est clean c'est propre et comme ça on se permet des choses

**Comment by r0one** [comment]
Ca me paraît très bien comme approche. Mais quand tu parles de scopes, ça n'a pas de rapport avec oauth, si? (Je me vois pas trop refresh les tokens selon la volonté de l'utilisateur)

**Comment by NastuzziSamy** [comment]
Non non ça n'a rien à voir, je parle de scopes niveau Laravel 
En fait @CdRom1 c'est des méthodes que tu peux appeler sur ton query builder. Ça te permet d'ajouter des conditions par exemple

**Comment by NastuzziSamy** [comment]
Implémenté depuis ce commit: 248a8341d14712193e5eb65d87c2d21df40ca5c7
