### ISSUE TITLE
Boutons de validation/rejet membres

### ISSUE THREAD

**Issue by jumelloic** [simde-utc/portail#123]
![image](https://user-images.githubusercontent.com/8875142/53595391-6c09da00-3b9d-11e9-8778-bb2672f9db06.png)

Le comportement des boutons validation/rejet est un peu particulier. Aucun membre n'est validé mais j'ai quand même le bouton pour 1 des membres...

Normalement je devrais pas voir apparaître ce petit 'valider' ;)

**Comment by huetremy** [comment]
Duplicate #109

**Comment by NastuzziSamy** [comment]
Il y a bien un souci dans la correction que j'ai faite hier.

Je push une PR mais en clair:
- Possibilité de valider n'importe qui tant qu'on était prez au semestre précédent
- L'affichage du coup n'est plus logique avec le back. Tout doit être validé par les nouveaux membres, avant c'était un peu chaotique
