### ISSUE TITLE
Mise en page [au moins sur Chrome]

### ISSUE THREAD

**Issue by sillydebs** [simde-utc/portail#124]
Salut !

Il y a un mini-hic sur deux pages : les images de la liste des services sont trop grandes, et il y a un scroll vertical dans les div de chaque pôle (page associations, certaines ont des images trop grandes) qui est pas trop pratique sur mobile comme sur PC.

C'est rien de grave, mais ça me gênait un peu.

Merci pour la nouvelle appli. :)

**Comment by NastuzziSamy** [comment]
Salut @sillydebs , merci de ton retour

Ca a été corrigé il y a maintenant une semaine, n'hésite pas à commenter s'il y a toujours un souci concernant cette issue :)
