### ISSUE TITLE
Pas possible de suivre puis rejoindre asso (et vice versa)

### ISSUE THREAD

**Issue by lerevelateurdesoucis** [simde-utc/portail#126]
Quand on clique sur 'Rejoindre' pour une asso, il y'a un message d'erreur quand on veut ensuite cliquer sur 'Suivre'. Pareil si on a cliqué sur suivre, on ne peut pas cliquer sur 'Rejoindre'.
C'est embêtant :'(

**Comment by huetremy** [comment]
Salut !
Rejoindre une asso implique la suivre, c'est pas très clair dans l'UI mais du coup c'est soir l'un soit l'autre.
