### ISSUE TITLE
Implémentation cimetière des asso back+front

### ISSUE THREAD

**Issue by Pomlodie** [simde-utc/portail#132]
Bien le bonjour !

Le cimetière des associations a t-il été détruit ? Si oui, comment cela se passe t-il pour faire renaître une asso' (en l'occurrence Espace Citoyen, dont la re-création sera votée en AG PSEC le 14/03) ?

**Comment by NastuzziSamy** [comment]
Salut !

Il n'est pas détruit, rien a été perdu. Mais il manque l'affichage du cimetière :)

La recréation est demandée par le PSEC sous convention et/ou PV d'AG

**Comment by Chostakovitch** [comment]
Bon les frérots on fait quoi

**Comment by Chostakovitch** [comment]
@NastuzziSamy allez frérot sois gentil

**Comment by Chostakovitch** [comment]
@MercierCorentin psartek

**Comment by r0one** [comment]
@Chostakovitch on attend ta PR couzin :)

**Comment by r0one** [comment]
Ca devrait être facile, les assos mortes sont exactement comme les actives, elles ont juste un tag morte en BDD. Il faut juste faire en sorte qu'elles soient lâchées par le back et gérer ça sur le front. Niveau UI, un slider de plus devrait faire l'affaire. Je laisse les gens motivés s'assigner l'issue.

**Comment by MercierCorentin** [comment]
@Chostakovitch tu peux review si tu veux ;p

**Comment by MercierCorentin** [comment]
Fixé par #300 et #284 
Mis en production ;)
