### ISSUE TITLE
Problème nom composé

### ISSUE THREAD

**Issue by jibecep** [simde-utc/portail#134]
Salut,
En raison d'un nom un peu trop long, la barre du haut cache en partie le menu des associations ce qui rend la navigation un peu complexe.

Merci !

![image](https://user-images.githubusercontent.com/48175793/53693934-7d263700-3da7-11e9-979d-44c61a592ff3.png)

**Comment by NastuzziSamy** [comment]
Salut !

C'est corrigé ! :) 

Merci pour ton retour
