### ISSUE TITLE
Services : des images un peu longues

### ISSUE THREAD

**Issue by AymanL** [simde-utc/portail#135]
![image](https://user-images.githubusercontent.com/40838419/53697535-62b58300-3dd2-11e9-8e4d-d26362a14592.png)

**Comment by mglorion** [comment]
Yes, y'a une refacto UX/UI de la page qui arrive ASAP

**Comment by NastuzziSamy** [comment]
@AymanL @mglorion ça a été corrigé et amélioré avec ajout des images :)
