### ISSUE TITLE
Sidebar inaccessible sur Android (Chrome, Firefox)

### ISSUE THREAD

**Issue by cterence** [simde-utc/portail#142]
Sur Asus Zenfone 5 avec Chrome & Firefox, on ne peut pas accéder à la sidebar, donc aux différents onglets. On est donc obligé de passer sur la version ordinateur pour faire quoi que ce soit (même pour se connecter).
Je mets deux screenshots comparant la vue mobile (1) et la vue ordinateur (2) depuis le mobile.

![53626847_341714336551673_5857020289937833984_n](https://user-images.githubusercontent.com/25285508/53735746-1167cb00-3e88-11e9-88b7-e9be6f4b2afb.jpg)
![53476390_2262296364011248_8986323003558068224_n](https://user-images.githubusercontent.com/25285508/53735745-1167cb00-3e88-11e9-81bd-c3543173cc0d.jpg)

**Comment by NastuzziSamy** [comment]
Je pars dessus :)

**Comment by NastuzziSamy** [comment]
Version mobile faite et en prod: https://github.com/simde-utc/portail/pull/177 :)
