### ISSUE TITLE
Liens copiés dans le presse-papier

### ISSUE THREAD

**Issue by Fallstar** [simde-utc/portail#143]
Salut,
Je viens de remarquer que les liens dans les descriptions des assos ne sont pas des liens, mais sont copiés dans le presse-papier. 
Pourquoi ?

**Comment by NastuzziSamy** [comment]
Salut,

C'est un choix que j'avais pris parce que j'étais dans l'affichage simple des moyens de contact, si tu es chaud pour faire mieux, je te laisse ouvrir une PR ;)

**Comment by Fallstar** [comment]
Je t'avoue que j'ai pas encore regardé en détail, mais comment ça peut être plus simple de mettre un lien en presse-papier plutôt que de juste faire un lien normal ? :)

**Comment by NastuzziSamy** [comment]
En fait, chaque contact correspond à un type de contact (url, lien social, email, numéro de téléphone, localisation) et il était plus simple pour moi de faire un copier/coller plutôt que de faire un switch sur chaque type et en fonction du bon type générer le bon type.

Je le note en feature, c'est vrai que c'est légèrement déroutant

**Comment by Fallstar** [comment]
Ça marche, je comprends. :)

**Comment by NastuzziSamy** [comment]
@Fallstar , c'est géré, cf la PR :)
