### ISSUE TITLE
Migration vers le gitlab

### ISSUE THREAD

**Issue by Fallstar** [simde-utc/portail#144]
Salut,
Pourquoi GitHub alors qu'on a le GitLab de l'UTC ? Au moins tout le monde a déjà un compte et peut participer plus facilement que s'il faut passer par un site tiers comme GitHub.

**Comment by NastuzziSamy** [comment]
Re,

1. Tous les projets SiMDE sont sur Github. 
2. Les anciens peuvent y contribuer si besoin
3. La visibilité est intéressante/importante vu que nous sommes qu'étudiants
4. C'est un projet libre, chacun est libre d'y participer, UTC ou non.
5. Le projet ne se limite pas qu'au front et on a des "clients" extés qui pourraient avoir besoin d'avoir une info spécifique dans le code (je pense notamment à Tremplin qui pourrait s'interconnecté)
6. Parce que j'en avais envie et que c'est initialement mon projet haha

**Comment by Fallstar** [comment]
Ok, je note, je vais quand même faire quelques objections mais je conçois que tu ne les prenne pas en compte. Par contre un truc qui me gêne vraiment et qu'il faut prendre en compte, c'est que pour l'instant le lien « signaler un bug » renvoie ici, or tous les utilisateurs du Portail des Assos n'ont pas forcément de compte GitHub. Donc même si pour la partie dev ça reste du GitHub, il faut que les utilisateurs puissent facilement signaler des bugs, proposer des améliorations, etc... sans avoir à se créer de compte sur un site tiers. 

Sinon mes objections dont tu ne tiendras pas compte :
1. Ok, ça n'empêche pas de changer, en soi.
2. Les anciens peuvent avoir accès au Gitlab de l'UTC (C'est pas pratique certes, mais du coup ton argument tient bof)
3. Mouais, on a pas les même priorités, soit.
4. Ça ok, j'entends. Après y'a des moyens d'avoir des miroirs vers le GitLab de l'UTC et du coup permettre aux UTCéens de contribuer facilement ET aux autres de le faire sur GitHub. (Mais ok, ça peut être un peu relou à mettre en place.)
5. Tremplin ils ont accès au Gitlab de l'UTC. Sinon même chose qu'au dessus.
6. Pardon ? Faut savoir, c'est ton projet à toi ou un projet du SiMDE ? Parce que du coup le premier point ne tient plus, et faudra revoir tous les endroits où c'est marqué que c'est fait par le SiMDE. Même si c'est toi qui l'as fait initialement et en grosse partie (et je me plains, mais si, dans l'ensemble c'est pas mal ce que t'as fait), ça reste un projet du SiMDE, pas de Samy Nastuzzi. Donc cet argument tu peux te garder, merci.

**Comment by NastuzziSamy** [comment]
En fait j'aimerai bien savoir qui est derrière ce login, pour moi ton point de vue n'est pas objectif.

Pour le point "signaler un bug", pour des questions de temps et de priorités, on est resté simple, mais c'est vrai que ça pourrait être sympa.

1.2. Je ne vois aucun intêret à passer sur Gitlab et c'est plus simple pour tout le monde.
3. Certes.
4. Oui ca peut être embêtant ^^
5. J'avais pas l'info, mais Tremplin n'est qu'un exemple.
6. Je lead ce projet, je prends les décisions. C'est mon choix personnel et final, que ça plaise ou non en fait ;)

**Comment by Fallstar** [comment]
> En fait j'aimerai bien savoir qui est derrière ce login, pour moi ton point de vue n'est pas objectif.

Bah justement une des raisons pour lesquelles je pense que le Gitlab est mieux : On sait qui est qui. Ici, j'ai pas forcément de donner mon identité sur GitHub pour plein de raisons, même si je ne le cache pas, je suis Rémi (de Picasoft notamment, cela dit ce que je dis là n'a rien à voir avec Picasoft, c'est juste pour répondre à ta question.)
Quant à la non-objectivité de mon point de vue, bah je pense objectivement qu'utiliser des solutions libres et décentralisées est une meilleure chose que d'utiliser des solutions fermées et centralisées, je vais pas rentrer dans les détails, mais on peut en discuter si tu veux. Et vu que c'est un projet qui concerne en particulier les étudiants de l'UTC et qu'on a déjà une forge git sur laquelle tous les étudiants de l'UTC ont un compte, ça me semble à la fois mieux d'un point de vue éthique, mais aussi d'un point de vue pratique parce que tous les concernés pourraient contribuer facilement, sans avoir à se faire de compte ailleurs.

6. Tu sais que c'est exactement cette phrase qui fait mourir la plupart des projets libres ? :)
Que tu prennes la plupart des décisions, ouais, normal, c'est toi qui t'investis le plus et qui a la meilleure visibilité sur le projet. Ça on est d'accord. Par contre c'est un projet du SiMDE, et tu n'es pas le SiMDE. Donc que ça soit ton choix parce que tu es actuellement en charge de ce projet, au nom du SiMDE, oui. Mais ton choix personnel, on en a pas grand chose à faire en fait, et il est final jusqu'à ce quelqu'un d'autre vienne s'en occuper. Et le « Que ça plaise ou non », bah si ça ne plaît pas à l'AG du BDE, c'est pas toi qui prendras la décision. (Je parle pas de GitHub/Gitlab hein, ça on s'en branle. Mais sur la gouvernance du projet en général, même si y'a peu de chance que tu prennes de décisions contre l'avis de tout le monde, oublie pas que non, c'est pas ton projet, c'est un projet du SiMDE.)

**Comment by jsmrcaga** [comment]
Je pense que le choix de la plateforme est fait depuis le début et il n'y a littéralement aucune raison de la contester. GitHub reste une plateforme ouverte et accessible à tous au même titre que GitLab à l'exception du login CAS (qui, comme dit Samy, ne permet pas forcément aux anciens d'y accéder).

D'autre part GitHub propose un plan étudiant qui offre pas mal d'accords avec plusieurs entreprises, ce qui peut très facilement aux étudiants d'apprendre des nouvelles technos et des nouvelles facons de faire (en entreprise typiquement):
- Tests unitaires avec un runner (Travis CI par ex)
- Déploiements (DO, AWS, Heroku)
- Error reporting (Sentry)
 Et le tout gratuitement. Certes le gitlab de l'utc permettrait de faire du CI, mais soyons honetes ce n'est pas enterprise-ready à moins que tu travailles pour picasoft ou framasoft (j'exagère, pas besoin de revenir sur cette phrase).

Finalement les issues sont là pour 
- reporter des bugs
- proposer des améliorations dans la codebase
- proposer des nouvelles features
- report des breaking changes non vus
- etc.
Mais surtout pas pour demander un changement de plateforme pour le projet.

Cela dit tu es complètement libre de prendre le projet le cloner et le reupload sur tous les gitlab, bitbucket, raspi que tu voudras. Le SiMDE possède une orga GitHub avec les membres depuis plus de 2 ans (je sais bien j'ai été là lors de la création), du coup il n'y a pas de question de gouvernance sur le SiMDE et ses projets.

**Comment by Fallstar** [comment]
On en est plus sur ce débat @jsmrcaga, mais merci de ton intervention.
Pour les avantages de Gitlab par rapport à Github je les ai déjà mentionné plus haut (et pour avoir utilisé Gitlab en entreprise, si c'est totalement « entreprise-ready », même pour des grosses structures, avec de la CI, du deploiement, etc...), mais peu importe en fait.

À la base je demandais juste, ce à quoi Samy a très bien répondu, pourquoi c'était sur Github et pas sur le Gitlab (et non un changement de plateforme). Puis j'ai émis mes objections, en précisant bien qu'elles n'étaient pas à prendre en compte, mais le point que je voulais surtout soulever, auquel Samy a également répondu, c'était justement le fait qu'il faille un compte GitHub pour faire tout ce que tu as mentionné dans l'utilité des issues. Or, pour ce qui est du dev, ok, je comprends que ça reste sur GitHub, les gens qui dev ont souvent déjà un compte. Par contre pour l'utilisateur lambda qui trouve un bug, c'est pas pratique.

Ensuite la question de gouvernance que je soulevais, c'était pour faire remarquer à Samy que c'est un projet du SiMDE et non un projet personnel, et que si le SiMDE change et n'est plus d'accord avec la direction que Samy prend, c'est le SiMDE qui aura le dernier mot. Je ne dis pas que Samy fait mal son taf, bien au contraire, je lui dis juste de faire attention à la façon dont il voit le projet.

**Comment by NastuzziSamy** [comment]
@Fallstar, on est bien d'accord concernant la gouvernance du projet, les décisions globales je les prends en accord avec mon équipe, mon bureau mais aussi avec mon BDE. Cependant, ce que je voulais sous-entendre par "je lead le projet ... que ça plaise ou non" c'est à moi que les décisions techniques sont. J'ai fait le choix de Github et ça le restera tant que je lead au moins et clairement, tant que mon équipe de devs ne s'en plains pas, je ne changerai rien ^^ 

Merci pour ta franchise.

Sur ces derniers mots, je clos l'issue
