### ISSUE TITLE
Interface admin: problèmes

### ISSUE THREAD

**Issue by NastuzziSamy** [simde-utc/portail#146]
- [x] Type des assos non complété
- [ ] Gestion des accès, filtre bizarre
- [ ] Utilisateurs non filtrable
- [x] Gérer les images

**Comment by MercierCorentin** [comment]
@NastuzziSamy Tu peux aussi rajouter que le menu ressources dépasse de l'écran et qu'il est impossible de scroller pour accéder aux ressources de la fin d'alphabet.

**Comment by NastuzziSamy** [comment]
> @NastuzziSamy Tu peux aussi rajouter que le menu ressources dépasse de l'écran et qu'il est impossible de scroller pour accéder aux ressources de la fin d'alphabet.

C'est un bug du paquet, il faut juste update ou alors manuellement ouvrir l'onglet à gauche en entier :)

**Comment by MercierCorentin** [comment]
En quoi le filtre de gestion des accès est-il bizarre?
Pour les utilisateurs j'ai bien vu et c'est corrigé en local pour l'instant ;)

**Comment by MercierCorentin** [comment]
Utilisateurs, corrigé par https://github.com/simde-utc/portail/commit/1807f51397332e0e277c0349563525b8c6a85e42
Comme on ne trouve pas le filtre de la gestion des accès bizarre, l'issue est close, on la ré-ouvrira si besoin.
