### ISSUE TITLE
Impossible de créer un événement

### ISSUE THREAD

**Issue by Chostakovitch** [simde-utc/portail#150]
Salut,

Quand je clique sur Créer -> Événement il ne passe rien. Rien dans la console non plus. La création d'article fonctionne pour moi.

Merci d'avance :)

**Comment by K-nop** [comment]
La création d'événement ne marche pas pour moi non plus (même problème). Cependant la création d'article fonctionne mais pas la publication de l'article, quand je presse le bouton publier rien ne se passe.
Merci d'avance si vous pouvez fixer ça :)

**Comment by Chostakovitch** [comment]
Pareil, HTTP 422.
