### ISSUE TITLE
[UI] Débordement des blocs dans liste des assos

### ISSUE THREAD

**Issue by Cathaiste** [simde-utc/portail#162]
Débordement de certaines images et certains blocs dans la liste des associations comme on peut le voir dans les captures d'écrans suivantes : 
<br>
![image](https://user-images.githubusercontent.com/26376521/54071402-6af73d80-426c-11e9-8ad6-6aecc72184a9.png)<br>
![image](https://user-images.githubusercontent.com/26376521/54071413-85c9b200-426c-11e9-81d3-8d7d1b7bb39a.png)

**Comment by NastuzziSamy** [comment]
Merci pour ton retour ! 

Tu pourrais nous donner ton navigateur et sa version stp ?

**Comment by Cathaiste** [comment]
> Merci pour ton retour !
> 
> Tu pourrais nous donner ton navigateur et sa version stp ?

J'utilise Google Chrome
Version 72.0.3626.121 (Build officiel) (64 bits)

**Comment by Cathaiste** [comment]
Ah je n'avais pas vu mais ça fait peut-être référence à cette issue : https://github.com/simde-utc/portail/issues/124

**Comment by MercierCorentin** [comment]
Closed with #124
