### ISSUE TITLE
Portail inaccessible

### ISSUE THREAD

**Issue by aure45** [simde-utc/portail#165]
Salut,

il m'est impossible d'accéder au portail des associations quand je me connecte. L'image suivante s'affiche :

![whoops](https://user-images.githubusercontent.com/16798030/54074864-3c8f5780-4298-11e9-917d-42ca27319830.png)

Si je ne suis pas connecté, j'ai la page normale, mais bien sûr accès à rien.

![portail](https://user-images.githubusercontent.com/16798030/54074880-69436f00-4298-11e9-8615-81ef5d10cd82.png)

J'ai essayé plusieurs fois depuis que le nouveau portail est en place, et je me retrouve systématiquement devant la première image. Je précise que je suis doctorant (du coup peut-être statut spécial, mais je connais un autre doctorant pour qui le portail fonctionne).
Mon navigateur est Firefox sur Linux (ordi perso depuis mon appartement) ou WIndows 10 (ordi de l'UTC, connecté au réseau de l'UTC).

Merci à vous.

**Comment by NastuzziSamy** [comment]
Salut @aure45 merci de ton retour, tu fais parti du bug des HDS. Je vais voir pour fixer de manière permanante ce problème, désolé pour le dérangement

**Comment by NastuzziSamy** [comment]
J'ai tenté un fix manuel, je t'ai envoyé un email. J'attends ton retour pour clore l'issue :)

**Comment by aure45** [comment]
Cela fonctionne, merci !

**Comment by gfrisch** [comment]
Salut ! 
Meme probleme pour moi mais pas résolu

**Comment by NastuzziSamy** [comment]
@gfrisch ça devrait être définitivement corrigé pour toi, j'ai migré vers ton cas :)
