### ISSUE TITLE
Connection impossible

### ISSUE THREAD

**Issue by gfrisch** [simde-utc/portail#173]
Bonjour, 
Connection impossible pour ma part au portail par le CAS. Je retombe systématiquement sur la page "Whoops, looks like something went wrong".

**Comment by NastuzziSamy** [comment]
Salut @gfrisch !

Excuse nous pour ce bug, il a déjà été reporté https://github.com/simde-utc/portail/issues/165 et je suis en train de réfléchir à le corriger de manière permanante.

Malheureusement je suis un peu pris, ça risque de prendre la semaine
