### ISSUE TITLE
Bug sur l'outil trésorerie

### ISSUE THREAD

**Issue by K-nop** [simde-utc/portail#176]
Salut,
Je ne sais pas si c'est moi ou pas, mais j'ai l'impression qu'il est compliqué de créer son budget prévisionnel sur l'outil tréso. 
1er problème : on à pas accès au semestre "P19" (ça s'arrête à "A18")
2ème problème : j'ai l'impression qu'on ne peut pas rentrer les budgets dans les différentes catégories, tout simplement éditer le budget prévisionnel.
Merci pour tout ce que vous faîtes ;) 
![Outil Tréso](https://user-images.githubusercontent.com/48333351/54467727-47118b80-4787-11e9-9f83-8d7683877f16.jpg)

**Comment by NastuzziSamy** [comment]
Salut ! Merci :) 

Le problème ne vient pas du Portail et l'outil tréso est à laisser tomber pour plusieurs raisons, je laisse @CdRom1 expliquer
