### ISSUE TITLE
Le bouton asso->créer (article, événement) ne marche plus

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#185]
Je parle du bouton dans une asso où on a tous les droits.
![image](https://user-images.githubusercontent.com/18699331/54884586-3641d380-4e73-11e9-8a4f-d28d7a9bd58c.png)
après clic:
![image](https://user-images.githubusercontent.com/18699331/54884588-3f32a500-4e73-11e9-985b-568713d982ed.png)
Graphiquement, il semble que le bouton ouvre une liste vide.
Pourtant, le HTML a l'air correct:
```
<div><button type="button" class="nav-link admin dropdown-toggle btn btn-secondary">CRÉER</button><div class="dropdown-menu d-block"><a class="dropdown-item" href="/assos/choruts/article">Article</a><a class="dropdown-item" href="/assos/choruts/evenement">Évènement</a></div></div>
```

**Comment by NastuzziSamy** [comment]
Ca va être supprimé directement
