### ISSUE TITLE
Loggin error

### ISSUE THREAD

**Issue by huetremy** [simde-utc/portail#19]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_confirmed' in 'field list' (SQL: update `auth_cas` set `updated_at` = 2018-09-17 10:31:10, `is_confirmed` = 1 where `user_id` = d43a7550-a013-11e8-9927-c9c554295a2f)

**Comment by NastuzziSamy** [comment]
```bash
php artisan quick:clear
php artisan migrate:fresh --seed
```

Si le clear marche pas, faire: `php artisan migrate:fresh --seed` puis refaire les deux commandes

**Comment by huetremy** [comment]
`Swift_TransportException  : Connection could not be established with host smtp.mailtrap.io [Connection timed out #110]` on user seeding
