### ISSUE TITLE
[Interface] Donner quelques infos de contacts aux utilisateurs non connectés

### ISSUE THREAD

**Issue by Saxodwarf** [simde-utc/portail#205]
Les informations de contacts (site d'une asso, addresse mail, page facebook, ..) ne sont pas affichées chez l'utilisateur non connecté.

Cela peut être problématique pour les assos ayant des contacts avec des extérieurs (les assos d'évènementiel par exemple).

Bien que cela puisse être compréhensible d'un point de vue du respect de la vie privée, notamment pour l'affichage du numéro de téléphone renseignées chez certaines associations, afficher l'adresse du site de l'asso ne devrait pas être un problème.

**Comment by NastuzziSamy** [comment]
@Saxodwarf merci, c'était initialement prévu comme ça...

Je corrige ça :)

**Comment by Saxodwarf** [comment]
Super, merci :)

**Comment by NastuzziSamy** [comment]
@Saxodwarf je te laisse tester, c'est en prod :)
