### ISSUE TITLE
Chevauchement titre + bouton sur page Articles

### ISSUE THREAD

**Issue by GuillaumeDmns** [simde-utc/portail#214]
Le titre "Dernier article" et le bouton pour en créer un nouveau se chevauchent sur mobile (Firefox & Firefox Focus)

![Articles](https://user-images.githubusercontent.com/31383849/56308216-fe167380-6146-11e9-8eb0-2e4f6f3e2987.png)

**Comment by MercierCorentin** [comment]
@NastuzziSamy on le met où le bouton au moment du chevauchement? 
Comme ça?
![Capture du 2019-06-24 18-56-00](https://user-images.githubusercontent.com/46066895/60037531-0c868b80-96b2-11e9-89e7-606d6fd39c7c.png)

**Comment by GuillaumeDmns** [comment]
> @NastuzziSamy on le met où le bouton au moment du chevauchement?
> Comme ça?
> ![Capture du 2019-06-24 18-56-00](https://user-images.githubusercontent.com/46066895/60037531-0c868b80-96b2-11e9-89e7-606d6fd39c7c.png)

En dessous du titre c'est peut-être mieux non ?

**Comment by MercierCorentin** [comment]
C'est vrai qu'en haut c'est pas fou mais le bouton n'est pas un "dernier article" donc je me demande si c'est vraiment bien niveau organisation. Niveau design c'est mieux oui. @GuillaumeDmns une idée qui satisferait organisation de l'information et design?

**Comment by MercierCorentin** [comment]
Corrigé par #232 ! Merci pour ton issue!

**Comment by MercierCorentin** [comment]
Corrigé par #232 ! Merci pour ton issue!
