### ISSUE TITLE
Bouton "rejoindre"

### ISSUE THREAD

**Issue by AymanL** [simde-utc/portail#219]
Le bouton rejoindre reste disponible et clickable alors que je suis déjà dans l'asso

**Comment by r0one** [comment]
Bonjour @AymanL, est-ce que tu pourrais nous envoyer un screen ou (ton login et le nom de ton asso)?

**Comment by r0one** [comment]
Je n'arrive pas à reproduire le bug et l'issue est vieille, je suppose que le problème a été résolu.
