### ISSUE TITLE
Notifications ?

### ISSUE THREAD

**Issue by NastuzziSamy** [simde-utc/portail#22]
Manque énormément de notifications

**Comment by jjerphan** [comment]
C'est à dire ?

**Comment by jsmrcaga** [comment]
Si vous voulez j'avais fait un petit service open source/self hosted de notifications: https://github.com/jsmrcaga/notifik

Vous n'avez qu'a modifier 2-3 trucs pour qu'il insère dans une DB, et vous pouvez ajouter support pour safari (mêmes apis mais avec `window.safari` si je me trompe pas)

**Comment by NastuzziSamy** [comment]
La DSI possède déjà son propre serveur de notification, il faut qu'on voit avec eux pour l'utiliser avec le Portail. 

Sinon mon issue était surtout pour préciser que beaucoup de notifications ne sont pas écrites  dans le back (par exemple lors de l'inscription à une association). 

On a prévu de connecter le Portail avec la future application UTC/BDE

**Comment by r0one** [comment]
Trop flou. Ouvrir une issue par besoin de notification, pour pouvoir prioriser leur implémentation, et avoir une vision claire des tâches indépendantes à faire.
Exemples:
* étudier l'API du serveur PUSH de l'UTC et écrire du code dans le back pour utiliser les notifications laravel
* une notif de bienvenue lorsqu'on se connecte au portail pour la première fois c'est une autre tâche qu'on peut faire indépendamment, avant ou après, mais qui n'est pas urgente.

**Comment by NastuzziSamy** [comment]
> Trop flou. Ouvrir une issue par besoin de notification, pour pouvoir prioriser leur implémentation, et avoir une vision claire des tâches indépendantes à faire.
> Exemples:
> 
>     * étudier l'API du serveur PUSH de l'UTC et écrire du code dans le back pour utiliser les notifications laravel
> 
>     * une notif de bienvenue lorsqu'on se connecte au portail pour la première fois c'est une autre tâche qu'on peut faire indépendamment, avant ou après, mais qui n'est pas urgente.

Ce n'est pas la bonne raison pour fermer l'issue, mais une autre issue existe, c'est de toute manière à implémenter
