### ISSUE TITLE
Erreur 500 sur suppression de booking ou event, en API ou en interface admin

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#225]

**Comment by NastuzziSamy** [comment]
Tu peux me donner le code d'erreur @CdRom1

**Comment by r0one** [comment]
# Sur l'interface admin
## event
avec un post sur https://assos.utc.fr/admin/resources/events/l'uid avec les paramètres:
```
_method | delete
_token | letoken
```
j'obtiens:
état HTTP: `500 Internal Server Error`
réponse: ```
{
    "message": "Server Error"
}```
## booking
Exactement la même erreur, en faisant la même requête sur `https://assos.utc.fr/admin/resources/bookings/86501a30-830f-11e9-a065-2b80d4d1dab8`.
# Sur l'API
Je peux plus tester sur l'API, j'arrive plus à me connecter en user credentials pour une raison inconnue, j'ouvre une autre issue.

**Comment by NastuzziSamy** [comment]
C'est normal, les événements sont pour certains reliés à une résa

**Comment by r0one** [comment]
@NastuzziSamy je n'arrive pas à supprimer un `booking` et je n'arrive pas à supprimer un `event`. Je suis d'accord, la liaison de l'un à l'autre crée une dépendance, mais il faut quand même qu'on puisse supprimer au moins l'un des deux!

**Comment by r0one** [comment]
Il faut qu'on puisse supprimer la réservation PUIS l'événement. Je suis d'accord, une réservation sans événement, ça n'a pas de sens, par contre il faut qu'on puisse supprimer des réservations.

**Comment by NastuzziSamy** [comment]
Fixé :)
