### ISSUE TITLE
Pouvoir récupérer des ressources en bulk via l'API

### ISSUE THREAD

**Issue by courentin** [simde-utc/portail#228]
Ajouter la possibiliter de spécifier une liste d'ID sur les routes listant des ressources pour les filtrer.

**Comment by NastuzziSamy** [comment]
Je pense qu'on peut partir dans un premier temps sur ce que j'ai fait sur ma PR, faire un bulk générique un peu lent et optimisé la où c'est simple et souvent appelé. Je pense me cocu amuser au départ uniquement sur les lectures `index` et `show` et faire par la suite les écritures
