### ISSUE TITLE
API pour obtenir les permissions par défaut d'un rôle

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#238]
Il y a déjà quelques tentatives infructueuses dans [https://github.com/simde-utc/portail/pull/216](https://github.com/simde-utc/portail/pull/216).

On a déjà les contrôleurs et les méthodes exposant ça, et il existe déjà des API pour les permissions par défaut d'un utilisateur ou d'un client oauth. Il faut juste créer proprement les routes pour accéder aux mêmes ressources, mais dans le cas d'un rôle. Mais comme je ne connais pas le fonctionnement des permissions, j'ai peur de me lancer et de faire laisser des failles de sécurité. @NastuzziSamy il faudrait que tu me formes, sinon j'aimerais bien que tu le fasses.

Idéalement, en tant qu'admin, j'aimerais bien pouvoir demander le scope  `get-role-permissions` et avoir une route me donnant les permissions d'un rôle. Un cas d'utilisation: pour donner à tous les secrétaires le droit de réserver des salles, il faudrait que j'aie `manage-role-permissions` et que je patch /roles/uuid-du-secretaire/permissions avec `booking`

**Comment by NastuzziSamy** [comment]
Hey @CdRom1 , je n'ai pas otut compris mais ouaip, il faut absoluement que je communique dessus ! 
Un call soon serait l'idéal

**Comment by r0one** [comment]
Referenced in #203
