### ISSUE TITLE
Rétablir support MD sur articles

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#239]
Depuis page d'accueil:

![image](https://user-images.githubusercontent.com/18699331/60516001-18d79d80-9cdd-11e9-911d-8a5fd9cdae45.png)

uuid de l'article : `963682a0-8d54-11e9-b66d-35431b782f01`

**Comment by NastuzziSamy** [comment]
Fixed by https://github.com/simde-utc/portail/pull/262 :)

Pushed in prod soon :)
