### ISSUE TITLE
Translate everything into English

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#242]
Translate:
* variables
* comments

PR should be in English too but it's not urgent.

Please reference all files that should be translated in this issue.

Issue opened because of [https://github.com/simde-utc/portail/pull/237](https://github.com/simde-utc/portail/pull/237)

**Comment by r0one** [comment]
TO TRANSLATE:

- [x] issue https://github.com/simde-utc/portail/pull/240
- [x] Project first depth level
`app` folder  translation :
  - [x] `Admin`
  - [x] `Console`
  - [x] `Exceptions`
  - [x] `Facades`
  -  `Http`
    - [x] `.`,  `Middleware`, `Requests`
    - `Controllers` folder :
      - [x] `.`, `Auth`, `Passport`
      - `v1`
        - [x] `.`
        - [x] `Access`
        - [x] `Article`
        - [x] `Asso`
        - [x] `Booking`
        - [x] `Calendar`
        - [x] `Client`
        - [x] `Comment`
        - [x] `Contact`
        - [x] `Event`
        - [x] `Faq`
        - [x] `Group`
        - [x] `Location`
        - [x] `Partner`
        - [x] `Permission`
        - [x] `Role`
        - [x] `Room`
        - [x] `Semester`
        - [x] `Service`
        - [x] `User`
        - [x] `Visibility`
  - [x] `Interfaces`
  - [x] `Models`
  - [x] `Notifications`
  - [x] `Pivot`
  - [x] `Providers`
  - [x] `Services`
  - [x] `Traits`
- [x] `bootstrap` folder  translation
- [x] `config` folder  translation
- [x] `database` folder  translation
- [x] `docker` folder  translation
- [x] `documentation` folder  translation
- [x] `public` folder  translation
- [x] `resources` folder  translation
- [x] `routes` folder  translation
- [x] `storage` folder  translation
- [x] `tests` folder  translation

**Comment by MercierCorentin** [comment]
Maybe we can do a gitHub project?

**Comment by MercierCorentin** [comment]
There is nothing to translate in the storage and docker folders. Marked them as done.

**Comment by NastuzziSamy** [comment]
Wow guys, huge work, good job :)

**Comment by r0one** [comment]
So are we done with this issue?

**Comment by MercierCorentin** [comment]
There are two pull request to merge left, I'll finish today or tomorrow.
