### ISSUE TITLE
Duplicate rule in .eslintrc.json

### ISSUE THREAD

**Issue by MercierCorentin** [simde-utc/portail#244]
https://github.com/simde-utc/portail/blob/de375a42c7d221f283b5f5624e72cbffd4fac231/.eslintrc.json#L51

https://github.com/simde-utc/portail/blob/de375a42c7d221f283b5f5624e72cbffd4fac231/.eslintrc.json#L61

Which line should we keep?

**Comment by NastuzziSamy** [comment]
@MercierCorentin can you test the linter with and without this rule then? Enabled at 1 and disabled at 0. Take the enabled one if the result is the same (even if it should not)

**Comment by MercierCorentin** [comment]
We actually have three variable declarations in case statements:
```
/home/oem/portail/resources/assets/react/redux/store.js
  323:10  warning  Unexpected lexical declaration in case block  no-case-declarations
  346:10  warning  Unexpected lexical declaration in case block  no-case-declarations
  347:10  warning  Unexpected lexical declaration in case block  no-case-declarations
```
Do you think it's a better practice to avoid this?

**Comment by NastuzziSamy** [comment]
Ok, it was me, just enable it 😄
