### ISSUE TITLE
Asso home screen: 500 error for unconnected user 

### ISSUE THREAD

**Issue by MercierCorentin** [simde-utc/portail#245]
View association for a unconnected user returns a 500 error. 
Regression caused by #236

**Comment by NastuzziSamy** [comment]
Do you have more info the js console @MercierCorentin?

**Comment by MercierCorentin** [comment]
@NastuzziSamy here `user` is `false` when the user is not connected. 
https://github.com/simde-utc/portail/blob/fd0641cac42e20e490de3e61518ca09bcaf1f1e8/resources/assets/react/screens/Asso/index.js#L592
Currently fixing it!
