### ISSUE TITLE
Simuler une cotisation en développement

### ISSUE THREAD

**Issue by lvaroqui** [simde-utc/portail#268]
Pour pouvoir tester les différents éléments d'interface, il serait intéressant de pouvoir simuler la cotisation d'un utilisateur en mode développement.

**Comment by r0one** [comment]
Je ne suis pas certain de ce que j'avance*, mais il me semble qu'il y a un projet qu'il s'appelle fauxginger (ou un truc comme ça) qui permet de simuler la BDD des cotisants. Je te dis ça pour orienter le début de ta recherche dans les méandres des repos SiMDE, au cas où ça te permettrait de trouver tout seul ce que tu cherches, mais @NastuzziSamy et @Cerichar sont calés sur le sujet et pourront te dire exactement comment faire.

*À vrai dire, je ne sais même pas si les cotisants sont encore gérés par une BDD externe à ce jour.

Si l'outil en question existe bien, avant de fermer l'issue, ça serait chouette si tu pouvais écrire un peu de doc pour expliquer au nouveaux comme toi comment faire pour simuler des cotisants. Sinon, hé bien attendons une PR.

J'espère t'avoir aidé ^^

**Comment by lvaroqui** [comment]
Merci Romain !
J'ai effectivement trouvé le projet et ça marche bien :)
Je vais faire une PR pour essayer d'intégrer ça !
