### ISSUE TITLE
[réservation] Ne télécharger que les infos de réservation de la période affichée à l'écran

### ISSUE THREAD

**Issue by Saxodwarf** [simde-utc/portail#276]
Actuellement, la totalité des réservations effectuée **depuis la première entrée** est téléchargée, pour chacune des salles, lors  du chargement du calendrier de réservation.
Cela représente presque 4Mo de fichier json téléchargé à chaque chargement du calendrier pour l'instant, mais cette quantité de donnée ne fera mécaniquement qu'augmenter.

Il serait intéressant, afin de ne pas rendre cet outil complètement inutilisable sur le long terme (notamment depuis une connexion mobile), de ne télécharger que les réservations correspondant à la période affichée à l'écran, et de relancer un nouveau téléchargement au moment d'un changement de période pour compléter.

Enfin, je n'ai pas testé, mais la création d'un grand nombre de réservation, loin dans le futur, pourrait avoir pour conséquence néfaste, mais néanmoins discrète, l'alourdissement progressif de la page, surchargeant ainsi le serveur et allongeant de manière substantielle le temps de chargement du calendrier.

**Comment by NastuzziSamy** [comment]
Merci pour ton retour @Saxodwarf , c'est prévu que je le remasteries :)
