### ISSUE TITLE
Favorite section unclear name 

### ISSUE THREAD

**Issue by JorisPLA7** [simde-utc/portail#277]
The favorites services section is called "Mes services"
Which makes it quite unclear and hard to find for new users 
![image](https://user-images.githubusercontent.com/21616659/65373869-5b2ccd00-dc83-11e9-8880-709551ae88f0.png)

**Comment by NastuzziSamy** [comment]
I thought it was short and simple but ok

**Comment by MercierCorentin** [comment]
fixed by #282
