### ISSUE TITLE
Membre d'une asso en tant que permanencier

### ISSUE THREAD

**Issue by ppom0** [simde-utc/portail#281]
Est-ce qu'on pourrait s'inscrire à une asso avec le statut **Permanencier** ?
Par exemple, pour Véloc, je fais deux heures de permanence, et ça s'arrête là.
Merci
Paco

**Comment by MercierCorentin** [comment]
Salut Paco,
Tu peux maintenant rejoindre Véloc en tant que permanencier, on a ajouté ce rôle pour véloc.
Bonne journée à toi.
