### ISSUE TITLE
No ui for managing active user oauth authorizations per oauth client

### ISSUE THREAD

**Issue by lvaroqui** [simde-utc/portail#287]
La page "Mes applications" dans "Mon Profil" est vide, on ne peut donc pas gérer les droits OAuth accordées aux différentes applications.

**Comment by NastuzziSamy** [comment]
Merci @lvaroqui du retour, c'est pas encore dev mais c'est prévu initialement :/
Je le tag en tant que tâche urgente puisqu'il s'agit d'un droit utilisateur
