### ISSUE TITLE
No configuration for Ginger service

### ISSUE THREAD

**Issue by MercierCorentin** [simde-utc/portail#289]
The class for Ginger service has a lot of hardcoded values. I believe a configuration for Ginger service should be created.

File location : `app/Services/Ginger.php`

**Comment by davelima** [comment]
Hi! Except for const URL, what other hardcoded values we have on this file? I can create the configs for this service!

**Comment by MercierCorentin** [comment]
Here you have some values that could be put into a configuration :
https://github.com/simde-utc/portail/blob/99aaac888ed695c92443d87bf7f43973e67a44b2/app/Services/Ginger.php#L352-L354
Thanks for helping us!

**Comment by MercierCorentin** [comment]
@davelima I see that you're a new contributor, please read our documentation [here](https://simde.gitlab.utc.fr) and especially the contribution guide: https://simde.gitlab.utc.fr/documentation/#/portail/dev/contribute !

**Comment by noeamiot** [comment]
I just made a pull request that should do the job for some hardcoded values but I left the lines with the proxy as it would useless to put them in an environment var.
