### ISSUE TITLE
La side bar et l'onglet career affichent des associations en trop

### ISSUE THREAD

**Issue by noeamiot** [simde-utc/portail#331]
La side bar et l'onglet Career du profile affichent les associations même si l'utilisateur n'a pas été accepté dans celles-ci / s'l follow uniquement l'association.
Pour la side bar, je pense qu'il faudrait afficher dans un menu séparé celles où l'utilisateur est accepté / pas accepté / uniquement follower.
Pour l'onglet career, il faut uniquement afficher les associations où l'utilisateur est accepté.

**Comment by noeamiot** [comment]
Je viens de me rendre compte pour la sidebar, que la différence est actuellement faite entre les assos suivies (icone pouce) et les autres (icone mains serrées). Je propose plutôt que de les séparer, d'ajouter une nouvelle icône en fonction de si l'utilisateur a été accepté ou non.

**Comment by MercierCorentin** [comment]
Je trouve intéressant de pouvoir voir les assos qu'on a suivies lors des semestres précédents. Si on décide d'enlever les assos suivies de l'historique il faudrait également décider de où les mettre.
Pour la side bar je trouve que c'est une bonne idée, tu penses à un titre de sous-menu en particulier? Je pense à `Association suivies` là maintenant.
Aussi, cela fait un petit moment que je me dit que les liens utiiles devraient être en dessous des raccourcis, cela est-il une bonne idée? Peut-être pourrais-tu profiter de ce travail sur la sidebar pour changer cela en même temps.

**Comment by noeamiot** [comment]
Je viens de lire ton message, je vais revoir ma PR pour faire ces changements.
La solution que j'ai trouvé pour la sidebar c'est de rajouter une icone (cf photo)
![image](https://user-images.githubusercontent.com/25272468/75723301-519c9c00-5cdc-11ea-8d87-541d995c332d.png)

Pour la carrière, j'ai simplement caché les associations où l'utilisateur n'était pas un membre accepté mais en effet, je pourrais mettre les assos suivies dans un autre onglet ou avec un icone particulière. Je ferais un test et enverrai une capture d'écran.

**Comment by noeamiot** [comment]
En déplaçant les liens utiles j'ai aussi dû réfléchir a où placer les services favoris. Pour la sidebar, j'ai essayé de placer liens utiles entre "raccourcis" et "services favoris" (voir photo) 
![image](https://user-images.githubusercontent.com/25272468/75754109-64d75800-5d2c-11ea-9205-9e1c5dae456c.png)
Je pense que si je mettais liens utiles en dessous de services favoris, ils n'auraient plus été assez visibles ...

Pour l'onglet carrière, je pense que quelle association est suivie manque de clarté, sur la capture d'écran en dessous, j'ai rajouté un "rôle" association suivie.
![image](https://user-images.githubusercontent.com/25272468/75754989-0612de00-5d2e-11ea-8fdf-4ab62fa4c48b.png)

Pour les deux modifications, ce serait cool d'avoir des avis sur ce qui est le plus ergonomique.

**Comment by MercierCorentin** [comment]
Super les changements comme ça, on comprends mieux!
