### ISSUE TITLE
Asso member list: variable not instanciated in particular case

### ISSUE THREAD

**Issue by MercierCorentin** [simde-utc/portail#334]
Here at line 77:
https://github.com/simde-utc/portail/blob/32003b5e298ee4e6b2a2feb9cbe9c53beb25c2a3/resources/assets/react/screens/Asso/MemberList.js#L70-L85
The `semester` variable is not instantiated if the first possible semester is the right semester, it then provokes a 500 error.

**Comment by noeamiot** [comment]
So we juste need to initalize it at currentSemester right ?
