### ISSUE TITLE
Retirer un membre d'une association

### ISSUE THREAD

**Issue by Miz0ka** [simde-utc/portail#352]
N'importe quelle membre d'une association peut retirer un autre membre depuis la page du trombinoscope
Le bouton "Retirer" est cliquable et opérationel

**Comment by noeamiot** [comment]
Après un peu de recherche, j'ai trouvé que pour la suppression, l'ajout et la modification (du rôle) d'un membre d'une asso, la condition est que l'utilisateur qui effectue l'action ait au moins le même rôle (ou un rôle parent).

La première solution qui me vient à l'esprit serait que pour effectuer ce genre d'action, l'utilisateur ait un rôle strictement supérieur. Cela impliquerait que deux personnes ayant le même rôle ne puissent pas se virer entre elles ce qui me paraît plutôt logique ...

@MercierCorentin un avis là dessus ?
