### ISSUE TITLE
Branche develop inutile => A expliquer dans la doc

### ISSUE THREAD

**Issue by NastuzziSamy** [simde-utc/portail#38]
La branche develop ne nous sert à rien concrètement puisqu'on réalise maintenant des PRs qui sont reviews.

Branche develope à supprimer dès la prochaine version.

**Comment by cesar-richard** [comment]
Mmm j'aurais quand meme laissé la branche develop comme branche de pré-prod, et fait regulierement des releases qui elles sont envoyées a master (master etant donc toujours 100% stable)

**Comment by NastuzziSamy** [comment]
@cesar-richard, on dirait pas plutôt que la release d'un tag est une nouvelle version stable ?

**Comment by cesar-richard** [comment]
Si, mais ce tag je le placerais dans la branche master.
Tu valide toutes tes PR vers develop, ensuite tu testes que le logiciel global fonctionne, et si oui tu pr vers master ou tu créé un tag

**Comment by NastuzziSamy** [comment]
Oki bah on reste sur notre workflow.

Je close l'issue quand ce sera explicité dans la doc de developpement

**Comment by NastuzziSamy** [comment]
Explication ajoutée au README par @MercierCorentin
