### ISSUE TITLE
Problem in CAS connection vue/CAS connection

### ISSUE THREAD

**Issue by huetremy** [simde-utc/portail#5]
Error in the debugger : Loading failed for the <script> with source “http://localhost/js/app.js”.
Comes form file resources/views/layouts/app.blade.php

**Comment by huetremy** [comment]
When served : Source map error: request failed with status 404
Resource URL: http://localhost:8000/js/app.js
Source Map URL: bootstrap.js.map[Learn More]

**Comment by danousna** [comment]
Du coup c'est normal qu'il te fasse un loading failed en pas ```serve```. Il tape dans localhost/js/app.js mais ca marche que si tu ```serve```, du coup c'est un problème de chemin. Plus précisément ca viens de ```mix()``` dans ```app.blade.php```. 

Je propose en fix temporaire de remplacer par ```asset()```. Ca remettra la bonne interface mais il y a d'autres problèmes 404, à suivre ...

**Comment by danousna** [comment]
Solution : passer en ```php artisan serve``` obligatoirement.
