### ISSUE TITLE
AssoTableSeeder

### ISSUE THREAD

**Issue by jpennors** [simde-utc/portail#6]
Impossible d'ajouter l'attribut parent_id (mis en commentaire actuellement). Peut-on seeder avec des données que l'on crée dans le même seed ?

**Comment by danousna** [comment]
On peut peut-être le faire en faisant un tableau contenant toutes nos données et puis seeder à partir de ce tableau.

**Comment by huetremy** [comment]
Check la migration des visibilites sur develop
