### ISSUE TITLE
La navigation ne fonctionne plus après une page d'erreur

### ISSUE THREAD

**Issue by mglorion** [simde-utc/portail#64]
Après avoir rencontré une page d'erreur, le changement de page ne fonctionne plus.

Par exemple:
Aller sur une page asso, cliquer sur créer > article (sans en avoir les droits). La page d'erreur s'affiche.

![image](https://user-images.githubusercontent.com/22710239/52289855-2297e780-296f-11e9-971f-25c0a8a993a3.png)

Puis faire retour avec le browser, ou cliquer sur une des pages dans les raccourcis de la sidebar (evenements, services, associations, groupes).
L'URL change bien mais le contenu de la page n'est pas mis à jour (il faut forcément refresh la page).

![image](https://user-images.githubusercontent.com/22710239/52290100-a0f48980-296f-11e9-9e0b-99217c472295.png)

**Comment by NastuzziSamy** [comment]
Ca a été changé en page 500 indiquant qu'il y a eu une erreur. Il faudra améliorer l'affichage mais c'est normal qu'il faille recharger la page
