### ISSUE TITLE
Bug sur l'arbre des assos

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#76]
`/api/v1/assos?stages=0,2,tree`

Les assos sont bien en-dessous des pôles, mais aussi au même niveau que les pôles.
De plus, BDO et FDP sont au même niveau que le BDE.

**Comment by NastuzziSamy** [comment]
Bug corrigé. Je ne sais pas trop pourquoi ça affichait n'importe quoi mais ça ne le fait plus.

Par contre, dans les données envoyées, tu as les assos supprimées aussi. Il faudra trier dans l'appli
