### ISSUE TITLE
Erreur des requètes pour le trombinoscopes

### ISSUE THREAD

**Issue by pineaulo** [simde-utc/portail#77]
Le php plante lors de la requête suivante: [https://portail.nastuzzi.fr/api/v1/assos/073cf670-2f86-11e9-b4a0-b91252b2ec63/members?](https://portail.nastuzzi.fr/api/v1/assos/073cf670-2f86-11e9-b4a0-b91252b2ec63/members?)
Stack trace visible ici: [Stack Trace](https://pastebin.com/eJE6Sn7e)

**Comment by NastuzziSamy** [comment]
Hello, 

Sisi il marche bien, en fait le problème est que tu n'es pas connecté (message : "Aunauthenticated")

**Comment by pineaulo** [comment]
L'erreur affiché n'est pas celle-ci dans l'application, on a `Exception: Le type contributerBde n'existe pas !`

**Comment by NastuzziSamy** [comment]
J'avais mal lu désole, c'est normalement fixé

**Comment by pineaulo** [comment]
Je test tout de suite

**Comment by pineaulo** [comment]
Ça ne fonctionne toujours pas... 
Je t'ai mis [les logs json ici](https://pastebin.com/7HsRejHC) si ça peux t'aider :)

**Comment by NastuzziSamy** [comment]
Fixé ici: https://github.com/simde-utc/portail/pull/75
