### ISSUE TITLE
Notifications: champ created_by (et éventuellement icône) ?

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#85]
Créer ces champs dans les notifs (j'aimerais pouvoir les récupérer direct dans la requête genre /api/v1/user/notifications).

Merci <3

**Comment by NastuzziSamy** [comment]
La nation du "créateur" est une bonne idée pour la traçabilité aussi

Par défaut le créateur est l'utilisateur connecté. Dans le cas d'une création externe, c'est l'association/le service.

Pour l'icône j'ai plusieurs idées: 
- Possibilité de la spécifier nous-même => alerte aux trolls, aux oublis
- Calcul intelligent de l'icone => on se base sur le créateur (asso par exemple) pour récupérer son icone

Perso, je partirai sur ça:
Possibilité de fournir l'icone.
Si elle n'est pas fournie, on assigne celle du "créateur externe" ou alors de l'icone qui correspond au type de notif

**Comment by r0one** [comment]
j'adhère :)

**Comment by NastuzziSamy** [comment]
Fixé :)
