### ISSUE TITLE
Respect des sauts de lignes

### ISSUE THREAD

**Issue by FloChehab** [simde-utc/portail#92]
Hola camarades,

Je vous suggère de respecter les sauts de lignes des articles, c'est plus joli :yum: 

https://github.com/simde-utc/portail/blob/4f4aaf527d297b30001d89de69519f8fd48127cf/resources/assets/react/components/Article/Article.js#L31

Un petit `white-space: pre;` devrait permettre un quick fix.

**Comment by NastuzziSamy** [comment]
@FloChehab je te laisse PR :D

**Comment by FloChehab** [comment]
@NastuzziSamy le guide d'installation est beaucoup trop long pour que j'installe votre bête ; à quand un peu de Docker ?

**Comment by NastuzziSamy** [comment]
@FloChehab c'est fait pour la beauté de tes yeux
